apiVersion: 1

datasources:
  - name: IDS PostgreSQL
    uid: PAF660F95C478FB94
    type: postgres
    access: proxy
    url: postgres:5432
    database: ids_db
    user: ids_user
    secureJsonData:
      password: ids_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      user: ids_user
      timescaledb: false
    isDefault: true
